// <auto-generated />
using System;
using HalOS.Integration.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HalOS.Integration.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    [Migration("20260708084218_AddAuditLog")]
    partial class AddAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HalOS.BuildingBlocks.Infrastructure.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedOnUtc")
                        .HasDatabaseName("ix_audit_log_tenant_id_created_on_utc");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("HalOS.BuildingBlocks.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("ix_outbox_message_processed_on_utc");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("HalOS.Integration.Domain.Aggregates.HksNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_party_id");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("commission_amount");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_amount");

                    b.Property<decimal>("MarketFeeAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("market_fee_amount");

                    b.Property<DateTime>("NotifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notified_date");

                    b.Property<Guid>("ProducerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_party_id");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference_number");

                    b.Property<Guid>("SaleTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_transaction_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "SaleTransactionId")
                        .IsUnique();

                    b.ToTable("hks_notification", (string)null);
                });

            modelBuilder.Entity("HalOS.Integration.Domain.Aggregates.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_party_id");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("commission_amount");

                    b.Property<decimal>("CommissionVatAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("commission_vat_amount");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<Guid>("SaleTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_transaction_id");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scenario");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "SaleTransactionId")
                        .IsUnique();

                    b.ToTable("invoice", (string)null);
                });

            modelBuilder.Entity("HalOS.Integration.Domain.Aggregates.ProducerReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AgriWithholdingAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("agri_withholding_amount");

                    b.Property<Guid>("BuyerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_party_id");

                    b.Property<decimal>("FarmerSskAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("farmer_ssk_amount");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_amount");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<decimal>("NetPayable")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("net_payable");

                    b.Property<Guid>("ProducerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_party_id");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("receipt_number");

                    b.Property<Guid>("SaleTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_transaction_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "SaleTransactionId")
                        .IsUnique();

                    b.ToTable("producer_receipt", (string)null);
                });

            modelBuilder.Entity("HalOS.Integration.Domain.Aggregates.ProductPassport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("consignment_id");

                    b.Property<Guid>("ConsignmentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("consignment_item_id");

                    b.Property<string>("PassportCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("passport_code");

                    b.Property<Guid>("ProducerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_party_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit_code");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ConsignmentItemId")
                        .IsUnique();

                    b.ToTable("product_passport", (string)null);
                });

            modelBuilder.Entity("HalOS.Integration.Domain.Aggregates.ReceiptDeduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ProducerReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_receipt_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProducerReceiptId");

                    b.HasIndex("TenantId");

                    b.ToTable("receipt_deduction", (string)null);
                });

            modelBuilder.Entity("HalOS.Integration.Domain.ReadModels.ProducerTaxProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AgriWithholdingRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("agri_withholding_rate");

                    b.Property<decimal>("FarmerSskRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("farmer_ssk_rate");

                    b.Property<bool>("KeepsRecords")
                        .HasColumnType("boolean")
                        .HasColumnName("keeps_records");

                    b.Property<Guid>("ProducerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_party_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ProducerPartyId")
                        .IsUnique();

                    b.ToTable("producer_tax_profile", (string)null);
                });

            modelBuilder.Entity("HalOS.Integration.Domain.Aggregates.ReceiptDeduction", b =>
                {
                    b.HasOne("HalOS.Integration.Domain.Aggregates.ProducerReceipt", null)
                        .WithMany("Deductions")
                        .HasForeignKey("ProducerReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HalOS.Integration.Domain.Aggregates.ProducerReceipt", b =>
                {
                    b.Navigation("Deductions");
                });
#pragma warning restore 612, 618
        }
    }
}
