// <auto-generated />
using System;
using HalOS.Integration.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HalOS.Integration.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    partial class IntegrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HalOS.BuildingBlocks.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("ix_outbox_message_processed_on_utc");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("HalOS.Integration.Domain.Aggregates.ProducerReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AgriWithholdingAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("agri_withholding_amount");

                    b.Property<Guid>("BuyerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_party_id");

                    b.Property<decimal>("FarmerSskAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("farmer_ssk_amount");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_amount");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<decimal>("NetPayable")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("net_payable");

                    b.Property<Guid>("ProducerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_party_id");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("receipt_number");

                    b.Property<Guid>("SaleTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_transaction_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "SaleTransactionId")
                        .IsUnique();

                    b.ToTable("producer_receipt", (string)null);
                });

            modelBuilder.Entity("HalOS.Integration.Domain.Aggregates.ReceiptDeduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ProducerReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_receipt_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProducerReceiptId");

                    b.HasIndex("TenantId");

                    b.ToTable("receipt_deduction", (string)null);
                });

            modelBuilder.Entity("HalOS.Integration.Domain.ReadModels.ProducerTaxProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AgriWithholdingRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("agri_withholding_rate");

                    b.Property<decimal>("FarmerSskRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("farmer_ssk_rate");

                    b.Property<bool>("KeepsRecords")
                        .HasColumnType("boolean")
                        .HasColumnName("keeps_records");

                    b.Property<Guid>("ProducerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_party_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ProducerPartyId")
                        .IsUnique();

                    b.ToTable("producer_tax_profile", (string)null);
                });

            modelBuilder.Entity("HalOS.Integration.Domain.Aggregates.ReceiptDeduction", b =>
                {
                    b.HasOne("HalOS.Integration.Domain.Aggregates.ProducerReceipt", null)
                        .WithMany("Deductions")
                        .HasForeignKey("ProducerReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HalOS.Integration.Domain.Aggregates.ProducerReceipt", b =>
                {
                    b.Navigation("Deductions");
                });
#pragma warning restore 612, 618
        }
    }
}
