// <auto-generated />
using System;
using HalOS.Party.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HalOS.Party.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PartyDbContext))]
    [Migration("20260707183225_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HalOS.BuildingBlocks.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("ix_outbox_message_processed_on_utc");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("HalOS.Party.Domain.Aggregates.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("KeepsRecords")
                        .HasColumnType("boolean")
                        .HasColumnName("keeps_records");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tax_office");

                    b.Property<string>("Tckn")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("tckn");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Vkn")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("vkn");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Tckn")
                        .IsUnique()
                        .HasFilter("tckn IS NOT NULL");

                    b.HasIndex("TenantId", "Vkn")
                        .IsUnique()
                        .HasFilter("vkn IS NOT NULL");

                    b.ToTable("party", (string)null);
                });

            modelBuilder.Entity("HalOS.Party.Domain.Aggregates.PartyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("PartyId", "Type")
                        .IsUnique();

                    b.ToTable("party_role", (string)null);
                });

            modelBuilder.Entity("HalOS.Party.Domain.Aggregates.Party", b =>
                {
                    b.OwnsOne("HalOS.Party.Domain.ValueObjects.WithholdingProfile", "WithholdingProfile", b1 =>
                        {
                            b1.Property<Guid>("PartyId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AgriWithholdingRate")
                                .HasColumnType("numeric(7,4)")
                                .HasColumnName("agri_withholding_rate");

                            b1.Property<decimal>("FarmerSskRate")
                                .HasColumnType("numeric(7,4)")
                                .HasColumnName("farmer_ssk_rate");

                            b1.HasKey("PartyId");

                            b1.ToTable("party");

                            b1.WithOwner()
                                .HasForeignKey("PartyId");
                        });

                    b.Navigation("WithholdingProfile");
                });

            modelBuilder.Entity("HalOS.Party.Domain.Aggregates.PartyRole", b =>
                {
                    b.HasOne("HalOS.Party.Domain.Aggregates.Party", null)
                        .WithMany("Roles")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HalOS.Party.Domain.Aggregates.Party", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
