// <auto-generated />
using System;
using HalOS.ColdChain.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HalOS.ColdChain.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ColdChainDbContext))]
    [Migration("20260710101122_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HalOS.BuildingBlocks.Infrastructure.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedOnUtc")
                        .HasDatabaseName("ix_audit_log_tenant_id_created_on_utc");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("HalOS.BuildingBlocks.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("ix_outbox_message_processed_on_utc");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("HalOS.ColdChain.Domain.Aggregates.ColdStorageUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MaxTempC")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("max_temp_c");

                    b.Property<decimal>("MinTempC")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("min_temp_c");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("cold_storage_unit", (string)null);
                });

            modelBuilder.Entity("HalOS.ColdChain.Domain.Aggregates.SensorReading", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ColdStorageUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("cold_storage_unit_id");

                    b.Property<decimal?>("HumidityPercent")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("humidity_percent");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<decimal>("TemperatureC")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("temperature_c");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ColdStorageUnitId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ColdStorageUnitId", "OccurredAt");

                    b.ToTable("sensor_reading", (string)null);
                });

            modelBuilder.Entity("HalOS.ColdChain.Domain.Aggregates.SensorReading", b =>
                {
                    b.HasOne("HalOS.ColdChain.Domain.Aggregates.ColdStorageUnit", null)
                        .WithMany("Readings")
                        .HasForeignKey("ColdStorageUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HalOS.ColdChain.Domain.Aggregates.ColdStorageUnit", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
