// <auto-generated />
using System;
using HalOS.Sales.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HalOS.Sales.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260707184356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HalOS.BuildingBlocks.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("ix_outbox_message_processed_on_utc");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.CommissionCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("commission_amount");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("commission_rate");

                    b.Property<Guid>("SaleTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_transaction_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vat_amount");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id");

                    b.HasIndex("SaleTransactionId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("commission_calculation", (string)null);
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.Consignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DispatchNoteRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dispatch_note_ref");

                    b.Property<Guid>("ProducerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_party_id");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ProducerPartyId");

                    b.ToTable("consignment", (string)null);
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.ConsignmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("consignment_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("ConsignmentId");

                    b.HasIndex("TenantId");

                    b.ToTable("consignment_item", (string)null);
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.Deduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("rate");

                    b.Property<Guid>("SaleTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_transaction_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SaleTransactionId");

                    b.HasIndex("TenantId");

                    b.ToTable("deduction", (string)null);
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.SaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("LineAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_amount");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SaleTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_transaction_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("SaleTransactionId");

                    b.HasIndex("TenantId");

                    b.ToTable("sale_line", (string)null);
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.SaleTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_party_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<Guid?>("ConsignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("consignment_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_amount");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<bool>("IsWithinMarket")
                        .HasColumnType("boolean")
                        .HasColumnName("is_within_market");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("ProducerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_party_id");

                    b.Property<DateTime>("SoldAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sold_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "BuyerPartyId");

                    b.HasIndex("TenantId", "OperationId")
                        .IsUnique();

                    b.HasIndex("TenantId", "SoldAt");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("sale_transaction", (string)null);
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("net_amount");

                    b.Property<Guid>("SaleTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_transaction_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("SaleTransactionId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Status", "DueDate");

                    b.ToTable("settlement", (string)null);
                });

            modelBuilder.Entity("HalOS.Sales.Domain.ReadModels.ProducerRateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AgriWithholdingRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("agri_withholding_rate");

                    b.Property<decimal>("FarmerSskRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("farmer_ssk_rate");

                    b.Property<Guid>("ProducerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_party_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ProducerPartyId")
                        .IsUnique();

                    b.ToTable("producer_rate_profile", (string)null);
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.CommissionCalculation", b =>
                {
                    b.HasOne("HalOS.Sales.Domain.Aggregates.SaleTransaction", null)
                        .WithOne("CommissionCalculation")
                        .HasForeignKey("HalOS.Sales.Domain.Aggregates.CommissionCalculation", "SaleTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.ConsignmentItem", b =>
                {
                    b.HasOne("HalOS.Sales.Domain.Aggregates.Consignment", null)
                        .WithMany("Items")
                        .HasForeignKey("ConsignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.Deduction", b =>
                {
                    b.HasOne("HalOS.Sales.Domain.Aggregates.SaleTransaction", null)
                        .WithMany("Deductions")
                        .HasForeignKey("SaleTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.SaleLine", b =>
                {
                    b.HasOne("HalOS.Sales.Domain.Aggregates.SaleTransaction", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.Settlement", b =>
                {
                    b.HasOne("HalOS.Sales.Domain.Aggregates.SaleTransaction", null)
                        .WithOne("Settlement")
                        .HasForeignKey("HalOS.Sales.Domain.Aggregates.Settlement", "SaleTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.Consignment", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HalOS.Sales.Domain.Aggregates.SaleTransaction", b =>
                {
                    b.Navigation("CommissionCalculation");

                    b.Navigation("Deductions");

                    b.Navigation("Lines");

                    b.Navigation("Settlement");
                });
#pragma warning restore 612, 618
        }
    }
}
